/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visão;

import Conexao.ConexaoSingleton;
import Excecao.ColecaoException;
import Excecao.ConexaoException;
import Modelo.Usuario;
import Persistência.ColecaoDeUsuario;
import Persistência.UsuarioDAO;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guhwl
 */
public class TelaCadastro extends javax.swing.JFrame {
        

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
//        CadastroInputNome.setText("Gustavo");
//        CadastroInputSobrenome.setText("Henrique");
//        CadastroInputEmail.setText("guhloreto@gmail.com");
//        CadastroInputNascimento.setText("01/04/1998");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastroInputLabel = new javax.swing.JLabel();
        CadastroEmailLabel = new javax.swing.JLabel();
        CadastroSenhaLabel = new javax.swing.JLabel();
        CadastroConfirmarSenhaLabel = new javax.swing.JLabel();
        CadastroInputSobrenome = new javax.swing.JTextField();
        CadastroInputNascimento = new javax.swing.JTextField();
        CadastroInputSenha = new javax.swing.JPasswordField();
        CadastroInputConfirmarSenha = new javax.swing.JPasswordField();
        CadastroBotaoCadastrar = new javax.swing.JButton();
        CadastroBotaoVoltar = new javax.swing.JButton();
        CadastroInputNome = new javax.swing.JTextField();
        CadastroInputLabel1 = new javax.swing.JLabel();
        CadastroInputEmail = new javax.swing.JTextField();
        CadastroEmailLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CadastroInputLabel.setText("Nome");

        CadastroEmailLabel.setText("Data de Nascimento");

        CadastroSenhaLabel.setText("Senha");

        CadastroConfirmarSenhaLabel.setText("Confirmar Senha");

        CadastroBotaoCadastrar.setText("Cadastrar");
        CadastroBotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBotaoCadastrarActionPerformed(evt);
            }
        });

        CadastroBotaoVoltar.setText("Voltar");
        CadastroBotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBotaoVoltarActionPerformed(evt);
            }
        });

        CadastroInputLabel1.setText("Sobrenome");

        CadastroEmailLabel1.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadastroBotaoCadastrar)
                .addGap(33, 33, 33)
                .addComponent(CadastroBotaoVoltar)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastroInputLabel)
                            .addComponent(CadastroInputLabel1))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadastroInputSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(CadastroInputNome))
                        .addGap(177, 177, 177))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastroSenhaLabel)
                            .addComponent(CadastroConfirmarSenhaLabel)
                            .addComponent(CadastroEmailLabel)
                            .addComponent(CadastroEmailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CadastroInputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(CadastroInputNascimento)
                                .addComponent(CadastroInputConfirmarSenha))
                            .addComponent(CadastroInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastroInputLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroInputSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastroInputLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroEmailLabel1)
                    .addComponent(CadastroInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroInputNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastroEmailLabel))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroSenhaLabel)
                    .addComponent(CadastroInputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroConfirmarSenhaLabel)
                    .addComponent(CadastroInputConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroBotaoCadastrar)
                    .addComponent(CadastroBotaoVoltar))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroBotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBotaoVoltarActionPerformed
        TelaInicial TeladeInicio;
        TeladeInicio = new TelaInicial();
        this.dispose();
        TeladeInicio.setVisible(true);
    }//GEN-LAST:event_CadastroBotaoVoltarActionPerformed

    private void CadastroBotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBotaoCadastrarActionPerformed
        try {
            String pass = "";
            String passC = "";
            Connection con = ConexaoSingleton.getConexao();
            ColecaoDeUsuario cu = new UsuarioDAO(con);
            
            for (char c : CadastroInputSenha.getPassword()) {
                pass += c;
            }
            for(char c : CadastroInputConfirmarSenha.getPassword()) {
                passC += c;
            }
            
             if (pass.equals(passC)) {
                 Usuario u1 = new Usuario();
                 u1.setUsuario_nome(CadastroInputNome.getText());
                 u1.setUsuario_sobrenome(CadastroInputSobrenome.getText());
                 u1.setUsuario_email(CadastroInputEmail.getText());
                 u1.setUsuario_senha(pass);
                 
                cu.inserir(u1);
                limparCampos();
                
                JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso.");
             } else {
                 JOptionPane.showMessageDialog(rootPane, "Os valores inseridos nos campos senha e confirmar senha devem ser absolutamente iguais.");
                 CadastroInputSenha.setText("");
                 CadastroInputConfirmarSenha.setText("");
             }
        } catch (ConexaoException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível estabelecer a conexão com o banco de dados.");
        } catch (ColecaoException ex) {
            JOptionPane.showMessageDialog(rootPane, "O email cadastrado já existe, altere o email e tente novamente.");
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastroBotaoCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }
    
    public void limparCampos() {
                CadastroInputNome.setText("");
                CadastroInputSobrenome.setText("");
                CadastroInputEmail.setText("");
                CadastroInputNascimento.setText("");
                CadastroInputSenha.setText("");
                CadastroInputConfirmarSenha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroBotaoCadastrar;
    private javax.swing.JButton CadastroBotaoVoltar;
    private javax.swing.JLabel CadastroConfirmarSenhaLabel;
    private javax.swing.JLabel CadastroEmailLabel;
    private javax.swing.JLabel CadastroEmailLabel1;
    private javax.swing.JPasswordField CadastroInputConfirmarSenha;
    private javax.swing.JTextField CadastroInputEmail;
    private javax.swing.JLabel CadastroInputLabel;
    private javax.swing.JLabel CadastroInputLabel1;
    private javax.swing.JTextField CadastroInputNascimento;
    private javax.swing.JTextField CadastroInputNome;
    private javax.swing.JPasswordField CadastroInputSenha;
    private javax.swing.JTextField CadastroInputSobrenome;
    private javax.swing.JLabel CadastroSenhaLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}