/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visão;

import Conexao.ConexaoSingleton;
import Excecao.ColecaoException;
import Excecao.ConexaoException;
import Persistência.ColecaoDeUsuario;
import Persistência.UsuarioDAO;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author guhwl
 */
public class TelaUsuarioAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmIntermediaria
     */
    public TelaUsuarioAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TelaAdmIntermediariaCadastrar = new javax.swing.JButton();
        TelaAdmIntermediariaAlterar = new javax.swing.JButton();
        TelaAdmIntermediariaRemover = new javax.swing.JButton();
        TelaAdmIntermediariaSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaAdmIntermediariaCadastrar.setText("Cadastrar Produto");
        TelaAdmIntermediariaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaAdmIntermediariaCadastrarActionPerformed(evt);
            }
        });

        TelaAdmIntermediariaAlterar.setText("Alterar Produto");

        TelaAdmIntermediariaRemover.setText("Excluir Produto");

        TelaAdmIntermediariaSair.setText("Sair");
        TelaAdmIntermediariaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaAdmIntermediariaSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TelaAdmIntermediariaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TelaAdmIntermediariaCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TelaAdmIntermediariaRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TelaAdmIntermediariaSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(TelaAdmIntermediariaCadastrar)
                .addGap(18, 18, 18)
                .addComponent(TelaAdmIntermediariaAlterar)
                .addGap(21, 21, 21)
                .addComponent(TelaAdmIntermediariaRemover)
                .addGap(18, 18, 18)
                .addComponent(TelaAdmIntermediariaSair)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelaAdmIntermediariaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaAdmIntermediariaSairActionPerformed
        TelaInicial TelaDeInicio;
        TelaDeInicio = new TelaInicial();
        this.dispose();
        TelaDeInicio.setVisible(true);
//        try {
//            Connection con = ConexaoSingleton.getConexao();
//            ColecaoDeUsuario cu = new UsuarioDAO(con);
//            cu.finalizarSessao();
//            TelaInicial TelaDeInicio;
//            TelaDeInicio = new TelaInicial();
//            this.dispose();
//            TelaDeInicio.setVisible(true);
//        } catch (ConexaoException ex) {
//            Logger.getLogger(TelaUsuarioAdm.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ColecaoException ex) {
//            System.out.println("Não foi possível finalizar a conexão.");
//            Logger.getLogger(TelaUsuarioAdm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      
    }//GEN-LAST:event_TelaAdmIntermediariaSairActionPerformed

    private void TelaAdmIntermediariaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaAdmIntermediariaCadastrarActionPerformed
                TelaCadastroProduto TelaAdm;
                TelaAdm = new TelaCadastroProduto();
                this.dispose();
                TelaAdm.setVisible(true);
    }//GEN-LAST:event_TelaAdmIntermediariaCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarioAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TelaAdmIntermediariaAlterar;
    private javax.swing.JButton TelaAdmIntermediariaCadastrar;
    private javax.swing.JButton TelaAdmIntermediariaRemover;
    private javax.swing.JButton TelaAdmIntermediariaSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
